version: "3"
services:  
  mongodb-contact:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  mongodb-order:
    image: 'mongo:latest'
    ports:
      - "27018:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  contact-service:
    build: contact-service/
    command: 
     - "--spring.data.mongodb.host=mongodb-contact" 
     - "--spring.data.mongodb.port=27017"
     - "--api.maxArtificialLatency=5"
     - "--dataload.numberOfPersons=100"
     - "--spring.profiles.active=CORS"
    ports:
      - 8080:8080
    depends_on:
      - mongodb-contact
  order-service:
    build: order-service/
    command: 
     - "--spring.data.mongodb.host=mongodb-order" 
     - "--spring.data.mongodb.port=27017"
     - "--api.maxArtificialLatency=5"
     - "--spring.profiles.active=CORS"
    ports:
      - 8081:8081
    depends_on:
      - mongodb-order
  # web:
  #   depends_on:
  #     - contact-service
  #     - order-service
  #   build:
  #     context: uncle-sam-burger-shop-web
  #     target: builder
  #   ports:
  #     - 4200:4200
  #   volumes:
  #     - ./uncle-sam-burger-shop-web:/project
  #     - /project/node_modules

